server:
  port: 8081

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates: 
            - Path=/customer/**
        - id: order-service
          uri: lb://order-service
          predicates: 
            - Path=/order/**
        - id: order-service
          uri: lb://order-service
          predicates: 
            - Path=/cart/**
        - id: order-service
          uri: lb://order-service
          predicates: 
            - Path=/orderitem/**
        - id: order-service
          uri: lb://order-service
          predicates: 
            - Path=/payment/**
        - id: auth-service
          uri: lb://auth-service
          predicates: 
            - Path=/auth/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
          filters:
            - AuthFilter
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/category/**
          filters:
            - AuthFilter
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/review/**