server:
  port: 8080

spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/DaniCis/ProyectoFinalBackend_Kruger
          search-paths: config-data
  application:
    name: config-service
